### ISSUE TITLE
EPIC: Posts

### ISSUE THREAD

**Issue by HMuraja** [HMuraja/happiness-unleashed#14]
As a **user**, I can **make a post about my completed act of kindness, including a photo and text** so that **I can share my experience and inspire others**.

### USER STORIES
- [x] #58 
- [x] #59
- [ ] #17 
- [x] #60
- [x] #61

### Tasks
- [x] Design user interface for creating and submitting completed act of kindness posts.
- [x] Implement backend functionality to store and retrieve completed act of kindness posts.
- [x] Add support for uploading photos as part of completed act of kindness posts.
