### ISSUE TITLE
USER STORY: Landing Page

### ISSUE THREAD

**Issue by HMuraja** [HMuraja/happiness-unleashed#16]
Epic #10

As a **visitor to the app**, I can **landing page explains clearly the purpose of the app** so that **the purpose of the act is clear to user**.

### Acceptance Criteria:
- [x] **Acceptance Criteria 1:** The landing page of the app should prominently feature four daily acts of kindness.
- [x] **Acceptance Criteria 2:** Visitors should be able to view details about the daily acts of kindness, including its description and suggested actions and choose one of the four acts displayed.
- [x] **Acceptance Criteria 3:** The daily act of kindness should be randomized.

### Tasks
- [x] Design landing page layout to accommodate the daily act of kindness feature.
- [x] Implement backend functionality to fetch and display information about the daily act of kindness.
- [x] Set up randomization of acts of kindness displayed.
