### ISSUE TITLE
USER STORY: Posts Carousel

### ISSUE THREAD

**Issue by HMuraja** [HMuraja/happiness-unleashed#19]
As a **user**, I can **see a carousel of random posts at the top of the kindness post list** so that **I can enjoy a visually engaging highlight of community activities**.

### Acceptance Criteria:
- [ ] **Acceptance Criteria 1:** Users should have access to a carousel section at the top of the kindness post list.
- [ ] **Acceptance Criteria 2:** The carousel should display random posts from the community.
- [ ] **Acceptance Criteria 3:** Users should be able to navigate through the carousel to view different posts.

### Tasks
- [ ] Design user interface for the carousel section.
- [ ] Implement functionality to fetch random posts from the community.
- [ ] Integrate carousel navigation controls for users to browse through posts..

**Comment by stephendawsondev** [comment]
I'm going to close this as `won't have` because we have kind of opted for a list instead of a carousel.
