### ISSUE TITLE
USER STORY: Deploy Project

### ISSUE THREAD

**Issue by HMuraja** [HMuraja/happiness-unleashed#2]
As a **user** I can **access the application in web** so that **I can use and view it**

### Acceptance Criteria:
- [x] **Acceptance Criteria 1:** Application is deployed in Heroku.
- [x]  **Acceptance Criteria 2:**  Final version of the Application is up and running and error free in Heroku.

### Tasks
- [x] Create Heroku app
- [x] Deploy project
