### ISSUE TITLE
USER STORY: Login and logout 

### ISSUE THREAD

**Issue by HMuraja** [HMuraja/happiness-unleashed#3]
As a **user**, I can **log in to the app** so that **my acts of kindness and profile can be personalized**.

### Acceptance Criteria:
- [x] **Acceptance Criteria 1:** User can log in and out of the app.
- [x]  **Acceptance Criteria 2:**  User can view their profile.

### Tasks
- [x] Create log in

**Comment by stephendawsondev** [comment]
I'll close this one since it looks to be a duplicate
