### ISSUE TITLE
USER STORY: Install Django

### ISSUE THREAD

**Issue by HMuraja** [HMuraja/happiness-unleashed#4]
As a **developer** I can **generate functionalities for the app** so that **users get the best experience when using the app.**

### Acceptance Criteria:
- [x] **Acceptance Criteria 1:** create Django project.
- [x] **Acceptance Criteria 2:** Create Django app.

### Tasks
- [x] Create Django app.
- [x]  Create Django project.
