### ISSUE TITLE
USER STORY: Create User Account

### ISSUE THREAD

**Issue by HMuraja** [HMuraja/happiness-unleashed#51]
Epic #11 

As a **user** I can **create user account** so that **I can access more app features and save my information**

### Acceptance Criteria:
- [x] **Acceptance Criteria 1:** User can register a new account. 
- [x]  **Acceptance Criteria 2:**  User can successfully login.
- [x] **Acceptance Criteria 3:** User can successfully logout.

### Tasks
