### ISSUE TITLE
USER STORY: User Authentication Ease of Use

### ISSUE THREAD

**Issue by HMuraja** [HMuraja/happiness-unleashed#53]
Epic #11  

As a **user** I can **easily use and access user authentication functionalities** so that **app use is intuitive and easy  to use**

### Acceptance Criteria:
- [x] **Acceptance Criteria 1:** Authentication functionalities are easily accessible and visible for the user.
- [x]  **Acceptance Criteria 2:**  User receives clear feed back on interactions.

### Tasks
- [x] Create login form
- [x] Create Register form.
- [x] Create Logout form.
- [x] Add login, logout and register buttons to navbar.
- [x] Style login form.
- [x] Style Register form.
- [x] Confirm email login is working.
