### ISSUE TITLE
USER STORY: Posts Layout

### ISSUE THREAD

**Issue by HMuraja** [HMuraja/happiness-unleashed#60]
Epic #14 
As a **user** I can **at glance understand what the post is about** so that **I can easily view each post I am interested of**

### Acceptance Criteria:
- [x] **Acceptance Criteria 1:** Each post states act, author name and the descriptor text and optional image. 
- [x]  **Acceptance Criteria 2:**  Posts are uniformly formatted.
- [x] **Acceptance Criteria 3:** Text is legible.

### Tasks
- [x] Add user name to the post.
- [x] Implement posts as masonry/gallery wall instead on list.
- [x] Add pagination to the post list
#93

**Comment by stephendawsondev** [comment]
Well done, @zanettiprado !!! 🏆
