### ISSUE TITLE
USER STORY: Navbar

### ISSUE THREAD

**Issue by claudio-cruz** [HMuraja/happiness-unleashed#63]
Epic #10 

As a **user** I want **a responsive navigation bar on the home page** so that **I can easily navigate to different sections of the website.**

### Acceptance Criteria:
- [x] **Responsive Design:** 
- [x]  **Clear Navigation:**  
- [x] **Good Color Contract:** 

### Tasks:
- [x]  Link to Posts.
- [x]  Logo links to landing page/home.
- [x] Link to my profile 
- [x] Login, Signup button for unlogged users.
- [x] Logout button for logged in users.
- [x] Teams link
- [x] About link.
- [x] Acts link for superusers
