### ISSUE TITLE
USER STORY: View Profile

### ISSUE THREAD

**Issue by HMuraja** [HMuraja/happiness-unleashed#86]
As a **user** I can **view my profile** so that **I can see my information.**

### Acceptance Criteria:
- [x] **Acceptance Criteria 1:** Logged in user can view their profile. 
- [x]  **Acceptance Criteria 2:**  All information is correctly displayed.
- [x]  **Acceptance Criteria 3:**  Information is laid out nicely.

### Tasks
- [ ] Style Profile page.
